# Generated by Django 4.2.29 on 2026-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adetxinteg', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='In Stock', max_length=50),
        ),
    ]
